<h1>Some basic Python programming questions without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [51]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    r1=len(A)
    c1=len(A[0])
    r2=len(B)
    c2=len(B[0])
    if c1 != r2:
        print("Matrices are not comparitable for multiplication")
        return
    C = [[0] * c2 for _ in range(r1)]
    for i in range(r1):
        for j in range(c2):
            for k in range(c1):
                C[i][j]+=A[i][k]*B[k][j]
    return C
r1=int(input("Enter the number of rows of the matrix A : "))
c1=int(input("Enter the number of columns of the matrix A : "))
r2=int(input("Enter the number of rows of the matrix B : "))
c2=int(input("Enter the number of columns of the matrix B : "))
A = [[0]*c1 for _ in range(r1)]
B = [[0]*c2 for _ in range(r2)]
print("\nEnter the elements of A matrix")
for i in range(r1):
    for j in range(c1):
        A[i][j]=int(input("Enter the {} th row and {} th column element : ".format(i+1,j+1)))
print("\nEnter the elements of B matrix")
for i in range(r2):
    for j in range(c2):
        B[i][j]=int(input("Enter the {} th row and {} th column element : ".format(i+1,j+1)))
C=matrix_mul(A, B)
print("The matrices product is {}".format(C))

Enter the number of rows of the matrix A : 3
Enter the number of columns of the matrix A : 3
Enter the number of rows of the matrix B : 3
Enter the number of columns of the matrix B : 3

Enter the elements of A matrix
Enter the 1 th row and 1 th column element : 1
Enter the 1 th row and 2 th column element : 3
Enter the 1 th row and 3 th column element : 4
Enter the 2 th row and 1 th column element : 2
Enter the 2 th row and 2 th column element : 5
Enter the 2 th row and 3 th column element : 7
Enter the 3 th row and 1 th column element : 5
Enter the 3 th row and 2 th column element : 9
Enter the 3 th row and 3 th column element : 6

Enter the elements of B matrix
Enter the 1 th row and 1 th column element : 1
Enter the 1 th row and 2 th column element : 0
Enter the 1 th row and 3 th column element : 0
Enter the 2 th row and 1 th column element : 0
Enter the 2 th row and 2 th column element : 1
Enter the 2 th row and 3 th column element : 0
Enter the 3 th row and 1 th column element : 

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [64]:
from random import uniform
from functools import reduce
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    S=0.0
    for el in A:
        S += el
    B = [x/S for x in A]
    b=reduce(lambda c, x: c + [c[-1] + x], B, [0])[1:]
    r = uniform(0,1)
    for i in b:
        if r <= i:
            s = i
            n = b.index(s)
            return A[n]
    

def sampling_based_on_magnitued(A):
    for _ in range(0,100):
        number = pick_a_number_from_list(A)
        print(number)
A=[]

while True:
    a=input("Enter the elements of the matrix A : (To stop entering, enter N or n)")
    if a =='n' or a =='N':
        break
    A.append(int(a))
#A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
sampling_based_on_magnitued(A)

Enter the elements of the matrix A : (To stop entering, enter N or n)0
Enter the elements of the matrix A : (To stop entering, enter N or n)5
Enter the elements of the matrix A : (To stop entering, enter N or n)27
Enter the elements of the matrix A : (To stop entering, enter N or n)6
Enter the elements of the matrix A : (To stop entering, enter N or n)13
Enter the elements of the matrix A : (To stop entering, enter N or n)28
Enter the elements of the matrix A : (To stop entering, enter N or n)100
Enter the elements of the matrix A : (To stop entering, enter N or n)45
Enter the elements of the matrix A : (To stop entering, enter N or n)10
Enter the elements of the matrix A : (To stop entering, enter N or n)79
Enter the elements of the matrix A : (To stop entering, enter N or n)N
13
100
79
100
100
100
27
27
45
79
28
27
27
79
28
79
13
45
27
27
28
10
100
28
27
28
13
28
79
100
13
79
13
100
100
100
100
45
79
79
45
27
79
79
79
13
100
27
27
100
100
100
45
6
28
79
100
79
79
6
45
27
5
100
100
79

<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [77]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    y = re.findall("[0-9]",String)
    x = len(y)
    if not y:
        return(print('Empty string'))
    n = '#'
    return(print(n*x)) # modified string which is after replacing the # with digits
#A = '#2a$#b%c%561#'
A = input("Enter the string : ")
replace_digits(A)

Enter the string : #2a$#b%c%561#
####


<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [129]:
import math

def percentile(data, percentile):
    size = len(data)
    return data[int(math.ceil((size * percentile) / 100)) - 1]

def display_dash_board(students, marks):
    m = sorted(marks)
    n = sorted(range(len(marks)), key = lambda k: marks[k])
    g=[]
    print('\nA.\n')
    for i in range(len(m)-1,len(m)-6,-1):
        print(students[n[i]],m[i])
    print('\nB.\n')
    for i in range(5):
        print(students[n[i]],m[i])
    print('\nC.\n')
    p25 = percentile(m,25)
    p75 = percentile(m,75)
    for el in m:
        if el>=p25 and el<p75:
            g.append(m.index(el))
    if g[0]==g[-1]:
        g[-1]+=m.count(m[g[0]])-1
    for i in range(g[0],g[-1]+1):
        print(students[n[i]],m[i])
'''students = ['student1','student2','student3','student4','student5'\
            ,'student6','student7','student8','student9','student10']
marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80]'''
A = []
B = []
while True:
    a=input("Enter the students : (To stop entering, enter N or n) ")
    if a =='n' or a =='N':
        break
    A.append(a)
while True:
    a=input("Enter the marks : (To stop entering, enter N or n) ")
    if a =='n' or a =='N':
        break
    B.append(float(a))
display_dash_board(A, B)

Enter the students : (To stop entering, enter N or n) student1
Enter the students : (To stop entering, enter N or n) student2
Enter the students : (To stop entering, enter N or n) student3
Enter the students : (To stop entering, enter N or n) student4
Enter the students : (To stop entering, enter N or n) student5
Enter the students : (To stop entering, enter N or n) student6
Enter the students : (To stop entering, enter N or n) student7
Enter the students : (To stop entering, enter N or n) student8
Enter the students : (To stop entering, enter N or n) student9
Enter the students : (To stop entering, enter N or n) student10
Enter the students : (To stop entering, enter N or n) n
Enter the marks : (To stop entering, enter N or n) 45
Enter the marks : (To stop entering, enter N or n) 78
Enter the marks : (To stop entering, enter N or n) 12
Enter the marks : (To stop entering, enter N or n) 14
Enter the marks : (To stop entering, enter N or n) 48
Enter the marks : (To stop entering, enter 

<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [15]:
from scipy import spatial

def closest_points_to_p(S, P):
    D = []
    for i in S:
        D.append(spatial.distance.cosine(i,P))
    m = sorted(range(len(D)), key = lambda k: D[k])
    for i in range(5):
        print(S[m[i]])

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p(S, P)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [45]:
def i_am_the_one(red,blue,line):
    a = line.split('x',1)
    b = a[1].split('y',1)
    x = float(a[0])
    y = float(b[0])
    c = abs(float(b[1]))
    re = []
    bl = []
    if (float(red[0][0])*x + float(red[0][1])*y)<c:
        r=0
    else:
        r=1
    for i in range(len(red)):
        if r==0:
            if (float(red[i][0])*x + float(red[i][1])*y)<c:
                re.append((float(red[i][0])*x + float(red[i][1])*y)<c)
        else:
            if (float(red[i][0])*x + float(red[i][1])*y)>c:
                re.append((float(red[i][0])*x + float(red[i][1])*y)>c)
    for i in range(len(blue)):
        if r==0:
            if (float(blue[i][0])*x + float(blue[i][1])*y)>c:
                bl.append((float(blue[i][0])*x + float(blue[i][1])*y)>c)
        else:
            if (float(blue[i][0])*x + float(blue[i][1])*y)<c:
                bl.append((float(blue[i][0])*x + float(blue[i][1])*y)<c)
    if len(re)==len(red) and len(bl)==len(blue):
        return "YES"
    else:
        return "NO"

Red= [(1,1),(2,1),(4,2),(2,4),(-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [108]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def first(a):
    di = int(a[0])
    uc=0
    for i in range(len(a)):
        if i == 0:
            continue
        if a[i] == '_':
            uc+=1
        else:
            if i == len(a)-1:
                di = di + int(a[i])
            else:
                b=first(a[:(i+1)])
                for j in range(i+1):
                    a[j]=b[j]
                c=first(a[i:])
                l=i
                for i in range(len(c)):
                    a[l]=c[i]
                    l+=1
                if a.count('_')==0:
                    return a
                    
                
    for i in range(len(a)):
        a[i] = di//len(a)
    return a

def last(a):
    uc=0
    for i in range(len(a)):
        if a[i] == '_':
            uc+=1
        else:
            di = int(a[i])
            for j in range(i+1):
                a[j] = di//len(a[:(i+1)])
            if i == len(a)-1:
                return a
            else:
                b=(first(a[i:]))
                l=i
                for i in range(len(b)):
                    a[l]=b[i]
                    l+=1
                return a

def curve_smoothing(S):
    a=S.split(',')
    if a[0] != '_':
        a=first(a)
    else:
        a=last(a)
    return a#list of values

S=  input("Enter the comma separated string : ")
print(S)
smoothed_values= curve_smoothing(S)
print(smoothed_values)

Enter the comma separated string : _,_,30,_,_,_,50,_,_
_,_,30,_,_,_,50,_,_
[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [130]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
from fractions import Fraction
def compute_conditional_probabilites(A):
    sd = dict()
    pd = dict()
    a = []
    e = ['S1', 'S2', 'S3']
    x = [('F1', 'S1'), ('F1', 'S2'), ('F1', 'S3'), ('F2', 'S1')\
         , ('F2', 'S2'), ('F2', 'S3'), ('F3', 'S1'), ('F3', 'S2')\
         , ('F3', 'S3'), ('F4', 'S1'), ('F4', 'S2'), ('F4', 'S3'),\
         ('F5', 'S1'), ('F5', 'S2'), ('F5', 'S3')]
    b = []
    for el in A:
        a.append(el[1])
        b.append(tuple(el))
    for el in e:
        sd[el] = a.count(el)
    for el in x:
        pd[el] = b.count(el)
    for el in x:
        print("P(F={}|S=={}) = ".format(el[0],el[1]),Fraction(pd[el],sd[el[1]]))
    
        
            
    

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2']\
     ,['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

P(F=F1|S==S1) =  1/4
P(F=F1|S==S2) =  1/3
P(F=F1|S==S3) =  0
P(F=F2|S==S1) =  1/4
P(F=F2|S==S2) =  1/3
P(F=F2|S==S3) =  1/3
P(F=F3|S==S1) =  0
P(F=F3|S==S2) =  1/3
P(F=F3|S==S3) =  1/3
P(F=F4|S==S1) =  1/4
P(F=F4|S==S2) =  0
P(F=F4|S==S3) =  1/3
P(F=F5|S==S1) =  1/4
P(F=F5|S==S2) =  0
P(F=F5|S==S3) =  0


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [135]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    s1=S1.split()
    s2=S2.split()
    a = []
    b = []
    for el in s1:
        if el not in a:
            a.append(el)
    for el in s2:
        if el not in b:
            b.append(el)
    set_a = set(a)
    set_b = set(b)
    print(len(set_a & set_b))
    print(set_a - set_b)
    print(set_b - set_a)
    

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)
#print(#the above values)

7
{'first', 'F', '5'}
{'3', 'S', 'second'}


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [149]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    y=0
    for i in range(len(A)):
        y+=(A[i][0]*math.log10(A[i][1]))+((1-A[i][0])*(math.log10(1-A[i][1])))
    loss=(-1)*(1/len(A))*y
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
